#!/bin/bash
source .env
DATA_DIR=sequencer-observer-dir
EVM_NODE=https://relay.mainnet.etherlink.com 
pid=`ps -ef | grep octez-evm-node | grep -v grep | awk '{print $2}'`

if [[ "$1" = "up"  && -z "${pid}" ]]; then
    $NODE run observer --dont-track-rollup-node --data-dir $DATA_DIR --evm-node-endpoint $EVM_NODE --rpc-addr 0.0.0.0 --rpc-port 8545  --cors-headers "*" --cors-origins "*" $2 >> stdout_observer 2>&1 &
    pid=`ps -ef | grep octez-evm-node | grep -v grep | awk '{print $2}'`
    echo "Started evm node: ${pid}"
elif [[ "$1" = "up"  && -n "${pid}" ]]; then
    echo "There is already an evm node: ${pid}"
elif [[ "$1" = "down" && -z "${pid}" ]]; then
    echo "nothing to kill"
elif [[ "$1" = "down" && -n "${pid}" ]]; then
    echo "killed $pid"
    kill -9 $pid
elif [[ "$1" = "patch" ]]; then
    $NODE patch kernel with $KERNEL --data-dir $DATA_DIR --force
fi
