#!/bin/bash
source .env
DATA_DIR=sequencer-sandbox-dir

pid=`ps -ef | grep octez-evm-node | grep -v grep | awk '{print $2}'`

if [[ "$1" = "up"  && -z "${pid}" ]]; then
     $NODE run sandbox --data-dir $DATA_DIR --rpc-addr 0.0.0.0 --rpc-port 8545 --initial-kernel installer.hex --time-between-blocks none --private-rpc-port 8546 --cors-headers "*" --cors-origins "*" $2 >> stdout_sandbox 2>&1 &
    pid=`ps -ef | grep octez-evm-node | grep -v grep | awk '{print $2}'`
    echo "Started evm node: ${pid}"
elif [[ "$1" = "up"  && -n "${pid}" ]]; then
    echo "There is already an evm node: ${pid}"
elif [[ "$1" = "down" && -z "${pid}" ]]; then
    echo "nothing to kill"
elif [[ "$1" = "down" && -n "${pid}" ]]; then
    echo "killed $pid"
    kill -9 $pid
elif [[ "$1" = "rup" ]]; then
    ./$0 down 
    wait
    ./$0 up $2
elif [[ "$1" = "patch" ]]; then
    $NODE patch kernel with $KERNEL --data-dir $DATA_DIR --force
fi
